version: '3'
services:
  controller:
    image: mwangxx/bulletjournal-backend:latest
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
